// GENERATED by scripts/generate-example-fixture.ts — do not hand-edit.
// Regenerate when public/dialogue_example.mp3 changes.
//
// Seeded into every new account so the first sign-in lands on something
// practisable. Everything expensive (transcription, punctuation, A/B labeling)
// was resolved once at generation time rather than per user.

import type { PersistedWhisperSegment } from '@/lib/sentence-split'

export type ExampleProjectData = {
  title: string
  audioOriginalName: string
  audioMimeType: string
  audioDurationMs: number
  segment: {
    title: string
    text: string
    startMs: number
    endMs: number
    whisperSegments: PersistedWhisperSegment[]
  }
}

export const EXAMPLE_PROJECT: ExampleProjectData = {
  "title": "サンプル · オフィスの会話",
  "audioOriginalName": "dialogue_example.mp3",
  "audioMimeType": "audio/mpeg",
  "audioDurationMs": 40040,
  "segment": {
    "title": "お昼の相談",
    "text": "A: すみません、今ちょっとお時間よろしいですか？\nB: はい、大丈夫ですよ。どうしました？\nA: 実は来週の会議の資料について、ご相談したいことがあって。\nB: ああ、あの件ですね。今日のお昼、一緒に食べながら話しましょうか。\nA: いいですね。何か食べたいものはありますか？\nB: そうですね。この前できた新しいラーメン屋、気になっていたんです。\nA: 私も聞いたことあります。評判いいみたいですね。\nB: じゃあ、12時に1階のロビーで待ち合わせしましょう。\nA: 了解しました。楽しみにしています。\nB: はい、では後ほど。",
    "startMs": 0,
    "endMs": 40040,
    "whisperSegments": [
      {
        "text": "すみません、今ちょっとお時間よろしいですか?",
        "startMs": 0,
        "endMs": 2760,
        "speaker": "A"
      },
      {
        "text": "はい、大丈夫ですよ。どうしました?",
        "startMs": 3620,
        "endMs": 5880,
        "speaker": "B"
      },
      {
        "text": "実は来週の会議の資料についてご相談したいことがあって。",
        "startMs": 6620,
        "endMs": 11220,
        "speaker": "A"
      },
      {
        "text": "ああ、あの件ですね。今日のお昼一緒に食べながら話しましょうか。",
        "startMs": 12080,
        "endMs": 16840,
        "speaker": "B"
      },
      {
        "text": "いいですね。何か食べたいものはありますか?",
        "startMs": 17400,
        "endMs": 20740,
        "speaker": "A"
      },
      {
        "text": "そうですね。この前できた新しいラーメン屋、気になっていたんです。",
        "startMs": 21760,
        "endMs": 26440,
        "speaker": "B"
      },
      {
        "text": "私も聞いたことあります",
        "startMs": 26440,
        "endMs": 28640,
        "speaker": "A"
      },
      {
        "text": "評判いいみたいですね",
        "startMs": 28640,
        "endMs": 30740,
        "speaker": "A"
      },
      {
        "text": "じゃあ12時に1階のロビーで待ち合わせしましょう",
        "startMs": 30740,
        "endMs": 34440,
        "speaker": "B"
      },
      {
        "text": "了解しました楽しみにしています",
        "startMs": 34440,
        "endMs": 37720,
        "speaker": "A"
      },
      {
        "text": "はいでは後ほど",
        "startMs": 37720,
        "endMs": 40040,
        "speaker": "B"
      }
    ]
  }
}
