// One-time generator for the example project every new account is seeded with.
//
// Run it only when `public/dialogue_example.mp3` changes:
//
//   npx tsx --conditions react-server --env-file=.env scripts/generate-example-fixture.ts
//
// It calls Whisper once for the chunk timings, then derives the A/B labels from
// SCRIPT below with the same aligner the app uses. Everything it produces is
// committed, so sign-up stays pure database inserts — no transcription, no
// speaker guessing, no audio cutting, per user.
//
// SCRIPT is hand-curated rather than LLM-punctuated: this dialogue is the first
// thing every new user sees, and the aligner needs the wording to match the
// transcript, so only punctuation and the A:/B: labels may be added here.

import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

import { transcribeAudioWithSegments } from '@/lib/groq'
import { whisperSegmentsToPersisted } from '@/lib/sentence-split'
import { alignSpeakersToScript } from '@/lib/speaker-align'

const AUDIO_FILE = 'dialogue_example.mp3'
const MIME_TYPE = 'audio/mpeg'
const PROJECT_TITLE = 'サンプル · オフィスの会話'
const SEGMENT_TITLE = 'お昼の相談'
const OUT_FILE = 'src/lib/example-project.data.ts'

const SCRIPT = [
  'A: すみません、今ちょっとお時間よろしいですか？',
  'B: はい、大丈夫ですよ。どうしました？',
  'A: 実は来週の会議の資料について、ご相談したいことがあって。',
  'B: ああ、あの件ですね。今日のお昼、一緒に食べながら話しましょうか。',
  'A: いいですね。何か食べたいものはありますか？',
  'B: そうですね。この前できた新しいラーメン屋、気になっていたんです。',
  'A: 私も聞いたことあります。評判いいみたいですね。',
  'B: じゃあ、12時に1階のロビーで待ち合わせしましょう。',
  'A: 了解しました。楽しみにしています。',
  'B: はい、では後ほど。',
].join('\n')

async function main() {
  const repoRoot = process.cwd()
  const audioBuffer = await readFile(path.join(repoRoot, 'public', AUDIO_FILE))
  console.log(`[example] read ${AUDIO_FILE} (${audioBuffer.byteLength} bytes)`)

  const whisper = await transcribeAudioWithSegments({
    audioBuffer,
    fileName: AUDIO_FILE,
    mimeType: MIME_TYPE,
  })
  console.log(`[example] transcribed ${whisper.segments.length} chunks, ${whisper.duration}s`)

  const chunks = whisperSegmentsToPersisted(whisper.segments)
  const whisperSegments = alignSpeakersToScript(chunks, SCRIPT)
  if (!whisperSegments) {
    console.error('[example] SCRIPT no longer matches the transcript. Raw chunks were:')
    for (const chunk of chunks) console.error(`  ${chunk.startMs}-${chunk.endMs} ${chunk.text}`)
    throw new Error('Update SCRIPT to match the audio, keeping the wording identical.')
  }

  console.log(`[example] ${whisperSegments.length} chunks labeled:`)
  for (const chunk of whisperSegments) {
    console.log(`  ${chunk.speaker ?? '-'} ${chunk.startMs}-${chunk.endMs} ${chunk.text}`)
  }

  const unlabeled = whisperSegments.filter((chunk) => !chunk.speaker).length
  if (unlabeled > 0) {
    throw new Error(`${unlabeled} chunk(s) ended up unlabeled — check SCRIPT covers the whole clip.`)
  }

  const audioDurationMs = Math.round(whisper.duration * 1000)

  const body = `// GENERATED by scripts/generate-example-fixture.ts — do not hand-edit.
// Regenerate when public/${AUDIO_FILE} changes.
//
// Seeded into every new account so the first sign-in lands on something
// practisable. Everything expensive (transcription, punctuation, A/B labeling)
// was resolved once at generation time rather than per user.

import type { PersistedWhisperSegment } from '@/lib/sentence-split'

export type ExampleProjectData = {
  title: string
  audioOriginalName: string
  audioMimeType: string
  audioDurationMs: number
  segment: {
    title: string
    text: string
    startMs: number
    endMs: number
    whisperSegments: PersistedWhisperSegment[]
  }
}

export const EXAMPLE_PROJECT: ExampleProjectData = ${JSON.stringify(
    {
      title: PROJECT_TITLE,
      audioOriginalName: AUDIO_FILE,
      audioMimeType: MIME_TYPE,
      audioDurationMs,
      segment: {
        title: SEGMENT_TITLE,
        text: SCRIPT,
        // The example is a single segment covering the whole clip, so it shares
        // the project's audio object instead of needing its own cut.
        startMs: 0,
        endMs: audioDurationMs,
        whisperSegments,
      },
    },
    null,
    2,
  )}
`

  await writeFile(path.join(repoRoot, OUT_FILE), body, 'utf8')
  console.log(`[example] wrote ${OUT_FILE}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
